name: Build, Test and Deploy a .NET Core WebApi to Azure App Service

env: # Change these settings when you need to
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 8.0.x
  PUBLISH_DIRECTORY: "./out/publish"

on:
  push:
    branches:
      - main
      - deployment
      - master
  workflow_dispatch: 

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if AZURE_WEBAPP_NAME secret exists"
        env:
          super_secret: ${{ secrets.AZURE_WEBAPP_NAME }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "❌ Secret AZURE_WEBAPP_NAME is missing."
          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
          exit 1

      - name: "Check if AZURE_WEBAPP_PUBLISH_PASSWORD secret exists"
        env:
          super_secret: ${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "❌ Secret AZURE_WEBAPP_PUBLISH_PASSWORD is missing."
          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
          exit 1

      - name: "Check if AZURE_WEBAPP_PUBLISH_USERNAME secret exists"
        env:
          super_secret: ${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "❌ Secret AZURE_WEBAPP_PUBLISH_USERNAME is missing."
          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
          exit 1

      - name: "Check if WEBAPI_PROJECT_NAME secret exists"
        env:
          super_secret: ${{ secrets.WEBAPI_PROJECT_NAME }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "❌ Secret WEBAPI_PROJECT_NAME is missing."
          echo "➡️ Maak hem aan bij Settings > Actions secrets and variables > Actions."
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./${{ secrets.WEBAPI_PROJECT_NAME }} --output ${{ env.PUBLISH_DIRECTORY }} --configuration Release

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}
  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Run migrations
        run: |
            Running 'dotnet ef database update' for project: littertracker-api
            ---------------------------------------------------------
            Tool 'dotnet-ef' (version 8.0.17 ) is installed.
            Project path: ./littertracker-api
            Looking for migrations...
            20250619191800_init20250619191800_init.Designer
            ApplicationDbContextModelSnapshot
            ...
            ---------------------------------------------------------
            Migration complete. No changes were applied.
  deploy:
    runs-on: ubuntu-latest
    needs: [check, build]
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: |
            <publishData>
              <publishProfile profileName="${{ secrets.AZURE_WEBAPP_NAME }} - Zip Deploy"
                publishMethod="ZipDeploy"
                publishUrl="${{ secrets.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net:443"
                userName="${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}"
                userPWD="${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}"
                destinationAppUrl="http://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"
                SQLServerDBConnectionString=""
                mySQLDBConnectionString=""
                hostingProviderForumLink=""
                controlPanelLink="https://portal.azure.com"
                webSystem="WebSites">
                <databases />
              </publishProfile>
            </publishData>
          package: '${{ env.PUBLISH_DIRECTORY }}'

  automated-api-tests:
    runs-on: ubuntu-latest
    needs: [check, build, deploy]
    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          attempts=0
          max_attempts=3
          success=false
          failed=false

          while [ $attempts -lt $max_attempts ]; do
            echo "Attempt $((attempts+1)) of $max_attempts"

            postman collection run 28008990-3203de5a-449a-41c8-bba0-59c06e61f88a -e 28008990-b2df6f73-d29d-43e4-805b-f902f1bb455f -i 28008990-13704902-2232-40b1-bf9f-b8dc2bbe9539 -i 28008990-272f7a6c-4b38-4c27-bbb9-cb9f0d12b29e -i 28008990-6305f6b6-c3cc-426d-9628-f6aeac627ac7 -i 28008990-f5ca2ca1-f640-463d-a2db-35d202b36c18 -i 28008990-124ce121-495f-4780-9780-a24849f34c1a -i 28008990-027b3a27-3f95-44e0-a411-f3a0621f66ee -i 28008990-0d2971e7-4175-4ef4-bf51-2dbd95a48680 -i 28008990-108c09b0-6bde-4a8a-8d87-fc169a2eea8f -i 28008990-59e48ff6-ad86-497e-95b3-959ba2770b1a -i 28008990-79b03528-bba3-4e65-beac-234bbe388674 -i 28008990-011a72b1-57dd-4226-b785-5b6bc9ebb06f -i 28008990-cc2c3878-8cb7-4077-afc4-5c883426644b -i 28008990-337b7910-1a26-4959-95da-54d6dafe09af -i 28008990-41d8012a-b642-400d-a855-a15d01d030d5 -i 28008990-a119e78d-bf15-4757-b128-0b724fba9d7c -i 28008990-066c606e-62a4-42d3-805c-ca11aab6e0ed -i 28008990-2cd9027e-af95-4149-8f8d-ebdac9e865bb -i 28008990-815368bd-85b6-42c4-b2f3-d9f344381c20 -i 28008990-92505fe8-768d-4627-8512-3d0c104a0751 -i 28008990-b4ee7d20-4928-432f-876b-7c7a8eaf0066 -i 28008990-ee0a33d1-e320-4c8c-ad3c-c7dd5b2e1908 -i 28008990-09955bb6-f9ec-4aae-8d2c-eb3da0abbd4e -i 28008990-f0443889-1b70-4b5b-8eea-5ad29b8ed306
            
            if [ "$failed" == "true" ]; then
              echo "Tests failed. Retrying..."
              attempts=$((attempts + 1))
              failed=false
            else
              success=true
              break
            fi
          done

          if [ "$success" == "false" ]; then
            echo "API tests failed after $max_attempts attempts."
            exit 1
          else
            echo "API tests passed successfully after $attempts attempts."
          fi
